cluster:
  nNodes: 2
  nodePool: np-1
network:
  useTcpx: "yes"
  ncclIfnames: 'eth0'
  ncclPlugin: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/nccl-plugin-gpudirecttcpx-dev:v3.1.6_2023_10_06
  rxdmContainer: us-docker.pkg.dev/gce-ai-infra/gpudirect-tcpx/tcpgpudmarxd-dev:v2.0.9
  disablePmtu: "yes"
workload:
  jobTimestamp: 1 # Must be defined
  gcsExperimentBucket: tejas_gpu # Must be defined
  experimentDir: llama2-7b-2nodes-bs1-original-stats
  gcsDataBucket: litgpt-public-bucket
  dataDir: openwebtext_dataset
  image: us-docker.pkg.dev/gce-ai-infra/litgpt-full/litgpt
  modelName: Llama-2-7b-hf
  batchSize: 1
  microBatchSize: 1
  warmupIters: 1
  maxIters: 5
  numBlocksToCombine: 1
  collectNsysProfile: 'yes' # Set to 'yes' for profiles
